### ISSUE TITLE
Tanks

### ISSUE THREAD

**Issue by jasmine-bae** [immersive-command-system/ImmersiveDroneInterface_2#143]
Aim: Get used to the Unity interface, tech stack, so you feel comfortable.

- Options:

     - https://learn.unity.com/project/roll-a-ball
     - https://learn.unity.com/project/tanks-tutorial

     - Or just clone the ISAACS repo and play around with it. 

Checkmark here when you have completed this assignment:

- [x] Akhil

- [ ] Amal

- [ ] Helena

- [ ] Karthik

**Comment by someonejazzy** [comment]
Aim: Get used to the Unity interface, tech stack, so you feel comfortable.

- Options:

     - [](https://learn.unity.com/project/roll-a-ball)

     - [](https://learn.unity.com/project/tanks-tutorial)

     - Or just clone the ISAACS repo and play around with it. 

Checkmark here when you have completed this assignment:

- [ ] Akhil

- [ ] Amal

- [ ] Helena

- [ ] Karthik

**Comment by erwang01** [comment]
done.
