### ISSUE TITLE
Setup Basic ServerConnection.cs

### ISSUE THREAD

**Issue by jasmine-bae** [immersive-command-system/ImmersiveDroneInterface_2#148]
Make sure to close issue when you have completed this task!

**Comment by erwang01** [comment]
- [ ] AddDrone() method.
- [ ] Test AddDrone method.
- [ ] Service calls and callbacks as defined in our [API document](https://docs.google.com/document/d/1g3dKYSgtFYrp6Fd4SA6JV8K353C8m3OqXH_cyjhj9-0/edit).
- [ ] Implement subscribers and logic to parse and update drone positions.

**Comment by erwang01** [comment]
Status Update 10/3: Skeleton is down.

Stateless Server Connection.

**Comment by jasmine-bae** [comment]
Completed (@peru)

-  Attach to world properties
-  Create ros variable instance with the server connection
-  Basic setup for the service calls
-  Add GetAllDrones service call
