### ISSUE TITLE
Setup Basic Drone_v2.cs

### ISSUE THREAD

**Issue by jasmine-bae** [immersive-command-system/ImmersiveDroneInterface_2#149]
Make sure to close issue when you have completed this task!

**Comment by erwang01** [comment]
- [x] Create drone gameobjects for each drone.
- [ ] Test waypoint logic.
- [x] User cycle through the drones properly (test)
- [x] Query for selected drone id upon user input and call appropriate method in ServerConnection.cs

**Comment by erwang01** [comment]
Stores State of each drone.

Uses RosBridge Lib.

@PeruDayani  will point to code to port.
