### ISSUE TITLE
Onboarding New Members (ROS)

### ISSUE THREAD

**Issue by varunsaran** [immersive-command-system/ImmersiveDroneInterface_2#150]
ROS Tutorial

If you have any questions please contact Eric, Peru, Jasmine, Nitzan or me.

Aim: Setup ROS, get the basics down, so you feel comfortable.

- ROS Overview: https://www.youtube.com/watch?v=qFVtJcGoJvw
- ROS setup: https://www.notion.so/Lab-0-Setting-up-Your-Virtual-Machine-213bc6fdcbdf43929b0b54251b937632
- ROS Tutorials: http://wiki.ros.org/ROS/Tutorials
    - (Tasks 1-21)

Checkmark here when you have completed the assignment.

- [x] Akhil
- [x] Amal
- [x] Helena
- [x] Karthik

**Comment by jasmine-bae** [comment]
Completed!
